import "quizpage.dart";

class QuizData {
  late Map quizData;

  Question question(
      String q, String op1, String op2, String op3, String op4, int correct) {
    List<Option> options = [
      Option(text: op1, isCorrect: (correct == 1) ? true : false),
      Option(text: op2, isCorrect: (correct == 2) ? true : false),
      Option(text: op3, isCorrect: (correct == 3) ? true : false),
      Option(text: op4, isCorrect: (correct == 4) ? true : false),
    ];
    options.shuffle();
    return Question(
      text: q,
      options: options,
    );
  }

  QuizData() {
    quizData = {
      "Our Universe - I": [
        question("What is the composition of ordinary matter in the universe?",
        "29%",
        "3%",
        "68%",
        "99%",
        2),
        question("Which of the following factors will affect the fate of the universe?",
        "Empty Void of Space",
        "Dark Matter",
        "Dark Energy",
        "Hawking Radiation",
        3),
        question("How many dimensions was the big bang singularity?",
        "0",
        "1",
        "3",
        "Infinite",
        1),
        question("How old is the universe?",
        "4 Quadrillion Years",
        "7 Billion Years",
        "14 Billion Years",
        "20 Million Years",
        3),
        question("What is the diameter of the observable universe?",
        "10 Quadrillion Kilometers",
        "7 Million Light Years",
        "96 Billion Light Years",
        "14 Billion Light Years",
        3),
        question("What is the composition of dark matter in the universe?",
        "99%",
        "3%",
        "50%",
        "28%",
        4),
        question("How will the universe be affected if gravity overcomes dark energy?",
        "Expansion of the universe will accelerate",
        "Expansion will slow down but later continue",
        "Expansion will slow down and the universe will shrink",
        "There will be no effects",
        3),
        question("In the early stages of the universe, for every 1 billion particles of antimatter, how much matter was present?",
        "1 Billion +",
        "1 Trillion +",
        "1 Million +",
        "Exactly 1 Billion",
        1),
        question("What is heat death?",
        "The universe dies due to shrinking",
        "The universe dies due to absence of stars",
        "The universe dies due to an explosion",
        "None of the above",
        2),
        question("What is the main effect of dark matter?",
        "Decelerating the expansion of the universe",
        "Accelerating the expansion of the universe",
        "Supporting the formation of galaxies",
        "Supporting the formation of planets",
        3)
      ],
      "Our Universe - II": [
        question("Name the theory that the universe maintains its average density while expanding constantly?",
        "The Big Bang Theory",
        "The Steady State Theory",
        "The Big Rip Theory",
        "None of the above",
        2),
        question("What is the composition of dark energy in the universe?",
        "3%",
        "33%",
        "68%",
        "99%",
        3),
        question("How many galaxies can be seen in the observable universe?",
        "1 Million",
        "1 Billion",
        "100 Billion",
        "1 Trillion",
        3),
        question("State the law responsible for the red shift of galaxies moving away from us?",
        "Hubble's Law",
        "Kepler's Law",
        "Johann's Law",
        "None of the above",
        1),
        question("How many dimensions at most does quantum mechanics predict?",
        "1",
        "4",
        "27",
        "Infinite",
        4),
        question("What is the acceleration of the universe?",
        "73 kmps/Mpc",
        "90 km/s^2",
        "9 ly/km",
        "1000 m/s^2",
        1),
        question("How many dimensions are currently known?",
        "1",
        "2",
        "3",
        "4",
        4),
        question("Approximately what percentage of galaxies are moving away from us?",
        "2%",
        "66%",
        "98%",
        "100%",
        3),
        question("Why do stars that move away from us have a red streak behind them?",
        "Due to gravitational forces",
        "Due to the stretching of light rays",
        "Due to black holes",
        "None of the above",
        2),
        question("What was the first element that formed in the early universe?",
        "Oxygen",
        "Helium",
        "Hydrogen",
        "Uranium",
        3)
      ],
      "Life of Stars - I": [
        question("How are stars born?",
        "As a result of supernovae",
        "Due to clumping of dust & gas",
        "Due to the effects of black holes",
        "Due to the effects of dark energy",
        2),
        question("In which of these structures are new-born stars prominent?",
        "Globular Clusters",
        "Open Clusters",
        "Stellar Nurseries",
        "Planetary Nebulae",
        3),
        question("How do the most massive stars in the universe die?",
        "Planetary Nebulae",
        "Type 1a Supernovae",
        "Type 1b Supernovae",
        "Type 2 Supernovae",
        4),
        question("In which unit is the luminosity of a star usually measured?",
        "Degree Celsius",
        "Degree Fahrenheit",
        "Solariums",
        "Solar Luminosities",
        4),
        question("What is the highest recorded surface temperature of a star?",
        "10 Thousand Degree Fahrenheit",
        "400 Thousand Degree Fahrenheit",
        "1 Million Degree Fahrenheit",
        "None of the above",
        2),
        question("What is the average life span of red dwarf stars?",
        "A few thousand years",
        "A few million years",
        "A few billion years",
        "A few trillion years",
        4),
        question("What is the last major element a massive star fuses before it starts fusing iron?",
        "Silicon",
        "Carbon",
        "Hydrogen",
        "Oxygen",
        1),
        question("How long does a star live for after it starts fusing iron?",
        "A few thousand years",
        "A few million years",
        "A few minutes",
        "Less than a minute",
        4),
        question("What is the star VY Canis Majoris classified as?",
        "A Main Sequence star",
        "A Red Dwarf star",
        "A Blue Supergiant star",
        "A Red Hypergiant star",
        4),
        question("What is a new born star called?",
        "Hyper star",
        "Supergiant star",
        "Protostar",
        "Baby star",
        3)
      ],
      "Life of Stars - II": [
        question("Name the diagram that divides stars on the basis of brightness and B-V index?",
        "HR Diagram",
        "Stellar Diagram",
        "Fusion Diagram",
        "None of the above",
        1),
        question("What is the last element a massive star fuses when it is close to the end of its life?",
        "Silicon",
        "Iron",
        "Oxygen",
        "Uranium",
        2),
        question("Approximately how long can a star live for after it starts fusing its final element?",
        "< 1 Minute",
        "10 Days",
        "1,000 Years",
        "1,000,000 Years",
        1),
        question("How long does a red supergiant star usually live for?",
        "A few thousand years",
        "A few million years",
        "A few billion years",
        "A few trillion years",
        2),
        question("At which stage is the star Sirius A currently in?",
        "Red Supergiant",
        "Blue Giant",
        "Protostar",
        "Main Sequence",
        4),
        question("How long can stars like our sun live?",
        "A few thousand years",
        "A few million years",
        "A few billion years",
        "A few trillion years",
        2),
        question("How long can black holes live for?",
        "Thousands of Years",
        "Millions of Years",
        "Billions of Years",
        "> 10^60 Years",
        4),
        question("Choose the correct sequence in which different elements are fused in stars.",
        "H, Si, Ne, O, Fe, He, C",
        "H, He, Fe, Si, Ne, C",
        "Fe, H, He, C, Si, Ne, O",
        "H, He, C, Ne, O, Si, Fe",
        4),
        question("Name the largest star currently known.",
        "VY Canis Majoris",
        "UY Scuti",
        "Betelgeuse",
        "WR 1018",
        2),
        question("What is the minimum temperature required for nuclear fusion to start in a star's core?",
        "15 Million Degree Celsius",
        "15 Thousand Degree Celsius",
        "10 Billion Degree Celsius",
        "1.5 Billion Degree Celsius",
        1)
      ],
      "Extreme Stars - I": [
        question("How much mass is present in a teaspoon of neutron star matter?",
        "Mass of a Car",
        "Mass of a House",
        "Mass of a Mountain",
        "Mass of the Earth",
        3),
        question("How thick is a neutron star's crust?",
        "Around 1 mm",
        "Around 1 inch",
        "Around 1 foot",
        "Around 1 km",
        2),
        question("What is a neutron star's atmosphere said to consist of?",
        "Solid Matter",
        "Hot Gases",
        "Ionized Plasma",
        "Bose-Einstein Condensate",
        3),
        question("How fast can a new born neutron star spin?",
        "2 times a second",
        "30 times a second",
        "70,000 times a minute",
        "40 times an hour",
        3),
        question("Which of these is the likely cause of a hyper-velocity star?",
        "A Pulsar",
        "A Magnetar",
        "A Black Hole",
        "A Supergiant Star",
        3),
        question("How fast can a neutron star spin if it has another star feeding it with matter?",
        "500 times a second",
        "700 times a minute",
        "20 times an hour",
        "None of the above",
        1),
        question("Name a more extreme version of neutron stars.",
        "Mega Stars",
        "Magnetars",
        "Quasars",
        "None of the above",
        2),
        question("Pick one characteristic of a pulsar.",
        "They are a few thousand kilometers in diameter",
        "They have beams of energy shooting out of their poles",
        "Both A & B",
        "None of the above",
        3),
        question("What would a star with the mass of five Suns turn into at the time of its death?",
        "White Dwarf",
        "Neutron Star",
        "Black Hole",
        "Black Dwarf",
        3),
        question("In which parts of a galaxy are super massive black holes mostly found?",
        "In the inner regions",
        "In the outer regions",
        "At the center",
        "In inter-galactic regions",
        3)
      ],
      "Extreme Stars - II": [
        question("Which one of these has the strongest magnetic field?",
        "Supergiant Stars",
        "Pulsars",
        "Magnetars",
        "Hyper-Velocity Stars",
        3),
        question("The most massive black hole found till date is located in which galaxy?",
        "Milky Way",
        "Andromeda",
        "Abell 85",
        "NGC 1512",
        3),
        question("To which planet's orbit would the hypergiant star UY Scuti extend if our Sun was to be replaced by it?",
        "Venus",
        "Mars",
        "Jupiter",
        "Neptune",
        3),
        question("What is a quasar?",
        "A regularly pulsing neutron star",
        "An object formed after the collision of two black holes",
        "An object formed after the collision of two neutron stars",
        "A black hole shooting out its unstable matter",
        4),
        question("What is the balance between the internal pressure of a star and its gravitational force called?",
        "Stellar Equilibrium",
        "Gravitational Balance",
        "Electromagnetic Balance",
        "Hydrostatic Equilibrium",
        4),
        question("What is the Chandrasekhar limit?",
        "The limit to the mass of a star beyond which it becomes a black hole",
        "The limit to the mass of a star beyond which it becomes a white dwarf",
        "The limit to the mass of a star beyond which it becomes a hypergiant star",
        "None of the above",
        1),
        question("In which of these cases is a black hole formed?",
        "When a white dwarf star dies",
        "When a supergiant star dies",
        "When a main sequence star dies",
        "None of the above",
        2),
        question("What is spaghettification?",
        "When two neutron stars collide, releasing a lot of energy",
        "When two stars collide, creating a black hole",
        "When an object is stretched due to intense gravity",
        "None of the above",
        3),
        question("What is the the event horizon?",
        "The outer plasmatic disk of a black hole",
        "The 'singularity' present in the black hole",
        "The 'point of no return' of a black hole",
        "None of the above",
        3),
        question("What is the diameter of the biggest black hole observed?",
        "1 Billion Kilometers",
        "78 Billion Miles",
        "90 Light Years",
        "70 Million Light Years",
        2)
      ],
      "Black Holes - I": [
        question("What is a quasar?",
        "Body formed due to the collision of black holes",
        "Body formed due to the collision of neutron stars",
        "A black hole shooting out its extra mass",
        "Stars travelling at very high speeds",
        3),
        question("What are the moderate particles of gravity called?",
        "Photons",
        "Gravitons",
        "Quarks",
        "None of the above",
        2),
        question("Which of these can result in the formation of a black hole?",
        "Travelling faster than the speed of light",
        "Compressing the Earth to 1/10 of its current size",
        "Pushing an object to its Schwarzschild Radius",
        "None of the above",
        3),
        question("A collision between which of the following objects can form a black hole?",
        "Asteroids",
        "Planets",
        "Planetesimals",
        "Neutron Stars",
        4),
        question("How do quasars promote star formation in galaxies?",
        "They push the gases in the central regions to the outer regions making it concentrated at a few areas",
        "They eject matter at the speed of light, hence compressing it and starting nuclear fusion",
        "They do not promote star formation, they actually prevent them",
        "None of the above",
        1),
        question("Which term best describes the shape and characteristics of our solar system?",
        "Geocentric",
        "Dwarfocentric",
        "Heliocentric",
        "None of the above",
        3),
        question("How were the planets in our solar system formed?",
        "The matter separated from the Sun formed the planets",
        "Dust and gas clumped together to form the planets",
        "The second star formed during the formation of the sun split into the planets",
        "None of the above",
        2),
        question("What is spaghettification?",
        "When two neutron stars collide, releasing a lot of energy",
        "When two stars collide, creating a black hole",
        "When an object is stretched due to intense gravity",
        "None of the above",
        3),
        question("How does increase in distance between two objects affect the gravitational force between them?",
        "It reduces the effect of gravity",
        "It increases the effect of gravity",
        "It does not affect it",
        "None of the above",
        1),
        question("What is the 'point of no return' in a black hole?",
        "The Singularity",
        "Accretion Disc",
        "Event Horizon",
        "None of these",
        3)
      ],
      "Black Holes - II": [
        question("How many dimensions does a singularity have?",
        "0",
        "1",
        "3",
        "Infinite",
        1),
        question("What is the limit of compression at the end of which a black hole is formed?",
        "Singularity",
        "Event Horizon",
        "Schwarzschild Radius",
        "Relativity",
        3),
        question("What is the diameter of the biggest black hole in the universe?",
        "78 Billion Miles",
        "70 Light Years",
        "98 Kilometers",
        "4 Light Years",
        1),
        question("What is the culmination of the four dimensions we know now called?",
        "Area-Time",
        "Space-Time",
        "Mass-Time",
        "None of these",
        2),
        question("Name the black hole present at the center of the Milky Way galaxy.",
        "HD-12957AG",
        "Abell 85",
        "Sagittarius A",
        "None of the above",
        3),
        question("How does intense gravity affect the passage of time (in relation to earth)?",
        "It speeds up the passage of time",
        "It slows down the passage of time",
        "It acts as an inter-dimensional portal to skip time",
        "None of the above",
        2),
        question("How do black holes die?",
        "By interacting with other black holes",
        "They die due to Hawking Radiation",
        "They turn into black dwarves after billions of years",
        "They do not die",
        2),
        question("Which one of these scientists predicted gravitational waves?",
        "Stephen Hawking",
        "Isaac Newton",
        "Albert Einstein",
        "Richard Feynman",
        3),
        question("Which of these formulae pointed towards the existence of antimatter?",
        "F = mv",
        "E = mc^2",
        "Q = ne",
        "None of the above",
        2),
        question("Why do objects that get sucked into black holes appear to be red?",
        "Light rays are stretched due to the intense gravity, making them turn red",
        "Light rays turn red due to the gamma radiation from black holes",
        "Gravitational ripples make the light appear red, they actually do not change color",
        "None of these",
        1)
      ],
      "Light & Time - I": [
        question("What term refers to the twinkling of stars?",
        "Scintillation",
        "Declination",
        "Reflection",
        "Parallax",
        1),
        question("How long does it take for a photon to reach the surface of the sun from its core?",
        "1 Second",
        "8 Minutes",
        "12 Minutes",
        "Thousands of Years",
        4),
        question("When was the theory of relativity composed?",
        "1700",
        "1905",
        "2000",
        "None of the above",
        2),
        question("At what percentage of the speed of light do the outer layers of a massive star collapse during its death?",
        "0.0003%",
        "1%",
        "33%",
        "None of these",
        3),
        question("What is the apparent magnitude of a star?",
        "The brightness of a star when seen from 10 parsecs away",
        "The brightness of a star when seen from the Earth",
        "The brightness of a star when seen from 1 light year away",
        "None of the above",
        2),
        question("Which one of these is the weakest of the four fundamental forces?",
        "Gravitational Force",
        "Electromagnetic Force",
        "Weak Nuclear Force",
        "Strong Nuclear Force",
        1),
        question("Which of the following is the most luminous star?",
        "Sun",
        "Betelgeuse",
        "Procyon",
        "Sirius",
        2),
        question("In what form does light travel?",
        "Wave form",
        "Particulate form",
        "Both A & B",
        "None of these",
        3),
        question("How much fuel would it require to accelerate to the speed of light?",
        "1 Million Tons",
        "1 Billion Tons",
        "1 Quadrillion Tons",
        "Infinite",
        4),
        question("What are the moderating particles of Electromagnetic forces?",
        "Gravitons",
        "Protons",
        "Photons",
        "None of these",
        3)
      ],
      "Light & Time - II": [
        question("What is a light year?",
        "Ten thousand years",
        "Time taken by light to travel one year into the future",
        "The distance travelled by a light ray in one year",
        "The age of the universe",
        3),
        question("Which of the following scientists proposed the theory of relativity?",
        "Carl Sagan",
        "Stephen Hawking",
        "Albert Einstein",
        "Isaac Newton",
        3),
        question("Is it physically possible to travel faster than the speed of light?",
        "Yes, it is possible when the mass is given enough acceleration",
        "Yes, it is possible as quasars expel matter at the speed of light",
        "No, it is physically impossible to travel faster than light",
        "None of the above",
        3),
        question("Which of the following factors can bend the fabric of space time?",
        "Gravity",
        "Velocity",
        "Nuclear Force",
        "None of these",
        1),
        question("What is the escape velocity of black holes?",
        "1000 km/s",
        "100000 km/s",
        "Faster than the speed of light",
        "None of the above",
        3),
        question("Which one of these is the strongest of the four fundamental forces?",
        "Electromagnetic Force",
        "Gravitational Force",
        "Weak Nuclear Force",
        "Strong Nuclear Force",
        4),
        question("Which one of these is not a part of the four fundamental forces?",
        "Electromagnetic Force",
        "Gravitational Force",
        "Nuclear Force",
        "Magnetic Force",
        4),
        question("What is the absolute magnitude of a star?",
        "The brightness of a star when seen from 10 parsecs away",
        "The brightness of a star when seen from 10 light years away",
        "The brightness of a star when seen from the Earth",
        "None of these",
        1),
        question("The rate of passage of time is :",
        "Same for everyone",
        "Different for everyone",
        "Relative to the speed of the observer",
        "None of the above",
        3),
        question("In the equation E = mc^2, what does 'c' stand for?",
        "Charge",
        "Change in Mass",
        "Speed of Light",
        "None of these",
        3)
      ],
      "Star Clusters - I": [
        question("Which is the biggest arm of the milky way galaxy?",
        "Orion Arm",
        "Sagittarius Arm",
        "Crux Arm",
        "None of the above",
        1),
        question("In approximately how many years will the Milky Way and the Andromeda collide?",
        "30000 Years",
        "4 Billion Years",
        "45 Million Years",
        "They won't collide",
        2),
        question("Name the dimmest celestial object visible to the naked eye in the night sky.",
        "Andromeda Galaxy",
        "Orion Nebula",
        "Triangulum Galaxy",
        "Procyon",
        3),
        question("Name the galaxy that will form after the collision of the Milky Way and the Andromeda.",
        "Andromeda Way",
        "Milkdromeda",
        "Milkdro Way",
        "None of the above",
        2),
        question("Name the smallest constellation in the night sky.",
        "Orion",
        "Hydra",
        "Leo",
        "Crux",
        4),
        question("What percentage of observable galaxies are moving away from us?",
        "2%",
        "70%",
        "45%",
        "98%",
        4),
        question("Which is the biggest type of star clusters?",
        "Open Clusters",
        "Globular Clusters",
        "Packed Clusters",
        "None of the above",
        2),
        question("Name the brightest star in the night sky.",
        "Polaris",
        "VY Canis Majoris",
        "Alpha Centauri",
        "Sirius",
        4),
        question("In which constellation is the the star Sirius located?",
        "Canis Minor",
        "Canis Major",
        "Hydra",
        "None of the above",
        2),
        question("Which is the closest galaxy to us?",
        "Andromeda",
        "Large Magellenic Cloud",
        "Small Magellenic Cloud",
        "None of these",
        2)
      ],
      "Star Clusters - II": [
        question("Which is the densest kind of star clusters?",
        "Stellar Associations",
        "Open Clusters",
        "Globular Clusters",
        "None of the above",
        3),
        question("Which constellation in the winter solstice is used to navigate other constellations?",
        "Scorpio",
        "Orion",
        "Leo",
        "Big Dipper",
        2),
        question("Which 3 stars compose the winter triangle?",
        "Sirius, Polaris & Procyon",
        "Sirius, Betelgeuse & Polaris",
        "Sirius, Betelgeuse & Procyon",
        "None of the above",
        3),
        question("Which galaxy is currently moving towards the Milky Way galaxy?",
        "Triangulum",
        "IC 1101",
        "Andromeda",
        "None of these",
        3),
        question("Which is the largest galaxy in the observable universe?",
        "IC 1101",
        "Andromeda",
        "Milky Way",
        "Triangulum",
        1),
        question("What is the diameter of the Milky Way Galaxy?",
        "1 Million Miles",
        "20000 Light Years",
        "100000 Light Years",
        "None of the above",
        3),
        question("In which constellation is the star Polaris located?",
        "Scorpio",
        "Orion",
        "Big Dipper",
        "None of the above",
        3),
        question("In which arm of the Milky Way is our solar system located?",
        "Orion Arm",
        "Sagittarius Arm",
        "Cygnus Arm",
        "None of these",
        1),
        question("Along with gravity what is the factor that affects the formation of galaxies?",
        "Dark Energy",
        "Black Holes",
        "Dark Matter",
        "None of the above",
        3),
        question("Name the biggest constellation in the night sky?",
        "Hydra",
        "Orion",
        "Big Dipper",
        "None of these",
        1)
      ],
    };
  }
}
